# Explore Raw qPCR Data

Script to explore raw qPCR data extracted from SDSv2.4.1 software

Author: Juvid Aryaman

Date: 09/04/18

In [21]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv('10-3-17.txt',skiprows=1,index_col=False, delimiter='\t') # data extracted from SDSv2.4.1 (Windows)

In [3]:
len(d)

135

In [4]:
d.head()

Well Nb Reporter  Rn          1           2          3           4  \
0        1  BJmmMUP NaN  112.40454  112.801740  114.18913  114.243866   
1        2  BJmmMUP NaN  112.32478  113.121826  114.06854  114.058210   
2        3  BJmmMUP NaN  116.14476  116.708600  117.62972  118.381260   
3       13  BJmmMUP NaN  121.62935  121.333220  122.21579  122.483830   
4       14  BJmmMUP NaN  131.28366  130.744480  132.16678  132.395230   

            5          6           7    ...           36.1        37.1  \
0  114.132935  114.92890  115.920410    ...      229.46020  230.367680   
1  114.457380  115.20325  115.562965    ...      231.69847  232.955430   
2  118.339770  119.13867  119.804726    ...      240.97644  242.385100   
3  122.715680  123.19760  123.390150    ...       72.30327   98.126710   
4  132.329800  133.22170  133.629320    ...       62.31851   89.178246   

         38.1       39.1       40.1       41.1       42.1       43.1  \
0  232.383670  231.88568  233.91666  233.56757  234.24258  235.38489   
1  233.430040  234.82362  235.83067  236.32652  237.30360  237.95287   
2  244.027310  243.94257  245.13070  245.69452  246.89075  247.45758   
3  122.708410  142.54895  156.82874  166.96940  173.86862  178.82143   
4  115.108406  136.09244  151.86047  161.82341  170.15282  176.60817   

        44.1       45.1  
0  235.69635  237.54620  
1  238.15495  239.24830  
2  249.29565  249.29083  
3  181.34155  184.54863  
4  180.70409  186.21228  

[5 rows x 94 columns]

In [5]:
bkg_crr_cols = []
for c in d.columns:
    if '.' in c:
        bkg_crr_cols.append(c)

Columns with a `.1` have been background corrected

Extract the background-corrected fluorescence intensities for a particular well

In [6]:
d[d['Well Nb']==253][bkg_crr_cols]

1.1       2.1       3.1       4.1       5.1       6.1       7.1  \
84 -2.984391 -3.500936 -3.040934 -3.164336 -2.762225 -2.777626 -2.375027   

         8.1       9.1      10.1    ...          36.1        37.1       38.1  \
84 -2.458665 -1.858327 -1.587549    ...      84.45778  113.788086  140.14575   

         39.1       40.1      41.1       42.1       43.1      44.1       45.1  
84  159.53291  173.48251  182.1414  189.41588  195.12259  200.0211  205.79031  

[1 rows x 45 columns]

Each column is a cycle of qPCR and the value corresponds to the fluorescence intensity

## Standards

In [7]:
d2 = pd.read_csv('2-3-17.txt',skiprows=1,index_col=False, delimiter='\t')

In [8]:
len(d2)

325

In [9]:
d2.head()

Well Nb              Reporter  Rn          1          2          3  \
0        4  BJ-CYB C57 vs BGHBST NaN  164.93016  165.47037  166.28128   
1        5  BJ-CYB C57 vs BGHBST NaN  170.90295  171.10635  172.08871   
2        6  BJ-CYB C57 vs BGHBST NaN  168.07901  168.87598  169.41101   
3       10  BJ-CYB C57 vs BGHBST NaN  156.02202  157.19952  158.70087   
4       11  BJ-CYB C57 vs BGHBST NaN  165.05008  165.85837  166.85050   

           4          5          6          7    ...           36.1  \
0  167.09586  167.62007  168.57388  169.01128    ...      207.36713   
1  173.19324  174.42584  175.13208  176.05826    ...      212.63933   
2  170.38098  171.56290  172.24478  173.19957    ...      212.82428   
3  159.71198  160.72733  161.29160  162.21262    ...      215.85010   
4  167.61887  168.40940  169.34706  169.62027    ...      226.55970   

        37.1       38.1       39.1       40.1       41.1       42.1  \
0  212.22963  215.86534  218.02013  219.13194  220.00542  220.10802   
1  218.33392  223.39111  225.26724  226.70125  227.93593  227.53859   
2  219.14010  222.53200  224.79767  226.73643  227.24603  226.47572   
3  217.11096  217.79274  218.40620  218.89021  218.58160  219.63922   
4  227.88205  228.24231  228.69300  229.21631  229.29137  229.77153   

        43.1       44.1       45.1  
0  221.30870  220.51686  219.12270  
1  228.92640  230.10910  227.13321  
2  228.23068  228.31120  226.84561  
3  219.57635  220.71070  219.62819  
4  230.17888  230.72441  229.39189  

[5 rows x 94 columns]

In [12]:
d2.columns

Index([u'Well Nb', u'Reporter', u'Rn', u'1', u'2', u'3', u'4', u'5', u'6',
       u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16',
       u'17', u'18', u'19', u'20', u'21', u'22', u'23', u'24', u'25', u'26',
       u'27', u'28', u'29', u'30', u'31', u'32', u'33', u'34', u'35', u'36',
       u'37', u'38', u'39', u'40', u'41', u'42', u'43', u'44', u'45',
       u'Delta Rn', u'1.1', u'2.1', u'3.1', u'4.1', u'5.1', u'6.1', u'7.1',
       u'8.1', u'9.1', u'10.1', u'11.1', u'12.1', u'13.1', u'14.1', u'15.1',
       u'16.1', u'17.1', u'18.1', u'19.1', u'20.1', u'21.1', u'22.1', u'23.1',
       u'24.1', u'25.1', u'26.1', u'27.1', u'28.1', u'29.1', u'30.1', u'31.1',
       u'32.1', u'33.1', u'34.1', u'35.1', u'36.1', u'37.1', u'38.1', u'39.1',
       u'40.1', u'41.1', u'42.1', u'43.1', u'44.1', u'45.1'],
      dtype='object')

In [16]:
d2[d2['Well Nb']==7]

Well Nb Reporter  Rn          1           2          3          4  \
156        7   BJCOII NaN  100.29143  101.014206  101.60947  101.67997   

             5         6          7    ...           36.1       37.1  \
156  102.43781  102.9595  103.26898    ...      199.38976  199.11371   

          38.1       39.1       40.1       41.1       42.1       43.1  \
156  199.88177  199.20456  199.06982  198.40222  198.31964  198.47345   

          44.1       45.1  
156  198.91931  198.17612  

[1 rows x 94 columns]

In [24]:
for i in range(8):
    well_init = 7 + i*24
    well_fin = well_init + 3
    
    #x = d2[d2['Well Nb']==well_init]
    print(np.arange(well_init,well_fin))
    

[7 8 9]
[31 32 33]
[55 56 57]
[79 80 81]
[103 104 105]
[127 128 129]
[151 152 153]
[175 176 177]


In [19]:
x

Well Nb Reporter  Rn          1           2          3          4  \
156        7   BJCOII NaN  100.29143  101.014206  101.60947  101.67997   

             5         6          7    ...           36.1       37.1  \
156  102.43781  102.9595  103.26898    ...      199.38976  199.11371   

          38.1       39.1       40.1       41.1       42.1       43.1  \
156  199.88177  199.20456  199.06982  198.40222  198.31964  198.47345   

          44.1       45.1  
156  198.91931  198.17612  

[1 rows x 94 columns]

In [25]:
d2[d2['Well Nb']==270]

Well Nb              Reporter  Rn          1          2          3  \
116      270  BJ-CYB C57 vs BGHBST NaN  195.70865  197.13582  198.03128   

             4          5          6          7    ...          36.1  \
116  198.84732  199.75027  200.61972  200.99503    ...      165.5819   

          37.1       38.1       39.1       40.1       41.1       42.1  \
116  195.27275  216.04614  232.00452  242.51723  248.38658  252.72792   

          43.1       44.1       45.1  
116  254.70319  255.22415  255.58592  

[1 rows x 94 columns]